#!/bin/sh
#
# ip-down - This is called when a PPP link brings down the IP protocol
#

STATE_DIR=/var/state/ppp
STATE_FILE=${STATE_DIR}/${1}.state

if [ ! -r $STATE_FILE ]; then
	# Hmm, this should NEVER happen!
	logger "PPPd called ip-down script for an interface that has no state file"
else
	rm -f $STATE_FILE
fi
