#!/bin/sh
#
# ip-up - This is called when a PPP link brings up the IP protocol
#

STATE_DIR=/var/state/ppp
STATE_FILE=${STATE_DIR}/${1}.state

if [ -r $STATE_FILE ]; then
	# Hmm, this should NEVER happen!
	logger "BUG: PPPd called ip-up script for an interface that has a state file"
	# There is not much we can do about it, so clear the file
	rm -f $STATE_FILE
fi

echo "pppdev=$1" > $STATE_FILE
echo "ptydev=$2" >> $STATE_FILE
echo "speed=$3" >> $STATE_FILE
echo "localip=$4" >> $STATE_FILE
echo "remoteip=$5" >> $STATE_FILE
echo "ipparm=$6" >> $STATE_FILE


