#!/usr/bin/php -q

<?

ini_set("html_errors", 0);

$DEBUG_MODE = 0;

require_once("functions.php");
require_once("configfile.php");
require_once("runconfig.php");
require_once("stats.php");

$config = new FirewallConfig;

if (!$config->LoadConfigFile("/etc/config/sysconfig")) {
	print("Error loading config file.\n");
	die;
}

$config->WriteConfigFile("/tmp/running-config");

ProcessFullConfig($config);
InitStatsDB($config);
ExecutePostBoot($config);

?>
