<?
	include("includes/loadconfig.php");

	$dump = $_GET["dump"];
	

function DebugContents($dump) {

	global $configfile, $config_filename;
	
	switch($dump) {

		case "object":
			print_r($configfile);
			break;
		;;
		case "working":
			readfile($config_filename);
			break;
		;;
		case "iptables":
			passthru('/usr/sbin/iptables -L -n');
			break;
		;;
		case "reset":
			if (file_exists('/tmp/working-config')) {
				unlink('/tmp/working-config');
				print("Working config file reset");
			}
			break;
		;;
		default:
			print("</pre>This debug menu is intended to help diagnose problems and check on the status of the configuration generated by the web interface.<pre>");
	}
}

	ob_start();
	DebugContents($dump);	
	$page_text = ob_get_contents();
	ob_end_clean();

	$MenuTitle="Main Menu";
	include("includes/header.php");


?>

<table width="100%" id="table1">
	<tr>
		<td>
<pre>
<?
	print($page_text);
?>
</pre>
		</td>
	</tr>
</table>

<?
	include("includes/footer.php");
?>