#!/bin/sh

rc_add() {
        mkdir -p "$tmp"/etc/runlevels/"$2"
        ln -sf /etc/init.d/"$1" "$tmp"/etc/runlevels/"$2"/"$1"
}

if [ -f /etc/setup/answerfile ]; then
    echo "Running automated Coyote Linux install..."
    setup-alpine -f /etc/setup/answerfile
else
    echo "No Coyote Linux answerfile found, starting manual install..."
    setup-alpine
fi

