#!/bin/sh
#
# dhcpd_dump - This file is called to dump the Wolverine dhcp leases database
#              to flash

# Source the hardware config
. /opt/coyote/config/hwconfig


if [ -r /var/lib/dnsmasq.leases ]; then 

	mount_flash_rw
	cp /var/lib/dnsmasq.leases /opt/coyote/config/dhcpd/dnsmasq.leases
	mount_flash_ro
	sync

fi

