#!/bin/sh
#
# gencerts - Generates a the X.509 certificate 
#
# 10/9/2024 - Updates for Coyote Linux 3.1 running on Alpine Linux

. /opt/coyote/config/hwconfig

SERVER_NAME=`hostname`

cleanup() {

	rm -f req.pem	
	rm -f tmp.conf
	rm -f key.pem
	rm -f ${SERVER_NAME}.pem
	rm -f ${SERVER_NAME}_priv.pem
	rm -f ${SERVER_NAME}_cert.pem
}

cd /tmp

cat << EOF >> tmp.conf
 
[ req ]
 default_bits           = 1024
 default_keyfile        = key.pem
 distinguished_name     = req_distinguished_name
 string_mask            = nombstr
 prompt                 = no
 output_password        = 1234
 req_extensions         = v3_req
 
[ req_distinguished_name ]
 CN                     = $SERVER_NAME
 
[ v3_req ]
 nsCertType             = server
 basicConstraints       = critical,CA:false
 
EOF

gen_cert() {

echo

	echo "RSA Key and Cert generation --------------------------------------- "
	/usr/bin/openssl genrsa -out key.pem 1024 
	/usr/bin/openssl req -x509 -new -days 1460 -key key.pem -config tmp.conf -out ${SERVER_NAME}_cert.pem
	if ! [ $? = 0 ]; then
		echo "Openssl reported an error during key generation. Process aborted."
		cleanup
		exit 1
	fi	  
}

gen_key() {

	echo "Generating RSA 1024 bit private key.  If this process pauses for a "
	echo "long time, try pressing the CTRL and SHIFT keys randomly as this "
	echo "aids in the system generation of ramdom data needed by the key "
	echo "creation process."
	echo

	echo "RSA Key generation ------------------------------------------------ "
	/usr/bin/openssl genrsa -out key.pem 1024
	if ! [ $? = 0 ]; then
		echo "Openssl reported an error during key generation. Process aborted."
		cleanup
		exit 1
	fi	  
}

gen_req() {

	echo "Request Generation ------------------------------------------------ "
	/usr/bin/openssl req -new -config tmp.conf -key key.pem -out req.pem
	if ! [ $? = 0 ]; then
		echo "Openssl reported an error during key generation. Process aborted."
		cleanup
		exit 1
	fi	  
}

get_priv() {

	/usr/bin/openssl rsa -in key.pem -passin pass:1234 -out ${SERVER_NAME}_priv.pem
	if ! [ $? = 0 ]; then
		echo "Openssl reported an error during key generation. Process aborted."
		cleanup
		exit 1
	fi	  
}

part_to_dir() {

	chmod 600 ${SERVER_NAME}_priv.pem
	cp ${SERVER_NAME}_priv.pem /opt/coyote/config/ssl.d/

}

all_to_dir() {

	chmod 600 ${SERVER_NAME}_priv.pem
	cp ${SERVER_NAME}_priv.pem /opt/coyote/config/ssl.d/
	cp ${SERVER_NAME}_cert.pem /opt/coyote/config/ssl.d/
}

new() {
	mount_flash_rw
	gen_cert
	get_priv
	all_to_dir
	mount_flash_ro
}

$1
cleanup

