#!/usr/bin/php -q

<?

	require_once("functions.php");
	require_once("configfile.php");
	require_once("runconfig.php");

	$config = new FirewallConfig;

	if (!$config->LoadConfigFile("/tmp/running-config")) {
		print("Error loading running config file.\n");
		die;
	}

	SyncClock($config);

?>
